version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - custom
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mymail.ru
      PGADMIN_DEFAULT_PASSWORD: adminpassword
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 80:80
    networks:
      - custom
    restart: unless-stopped

  url_abbreviation_app:
    container_name: url_abbreviation_app
    image: url_abbreviation_app
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: 8080
      BASE_URL: "http://localhost:8080"
      REAL_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/postgres"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - custom
    restart: unless-stopped

  alembic_migrations:
    container_name: alembic_migrations
    image: alembic_migrations
    command: ./migrate.sh
    depends_on:
      - postgres
    environment:
      ALEMBIC_DATABASE_URL: "postgresql://postgres:postgres@postgres/postgres"
      REAL_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@postgres:5432/postgres"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    networks:
      - custom

networks:
  custom:
    driver: bridge

volumes:
  postgres:
  pgadmin:
